name: country_code_manager
description: "This package is used to get country code and country name from country code."
version: 1.2.0
repository: https://github.com/mrjake34/country_code_manager
homepage: https://www.efestech.com.tr

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0

flutter:
  assets:
    - locale/
    - flags/
